### ISSUE TITLE
German Language

### ISSUE THREAD

**Issue by ralfb32** [th1efx/AutoKit-CarPlay#2]
Dear Sir could you please include German Language in your Theme.
Thank you very much in advance

Please find attached the german translation. If something is missing I'm willig to add this information

[German Translation.txt](https://github.com/th1efx/AutoKit-CarPlay/files/6236345/German.Translation.txt)

**Comment by th1efx** [comment]
I have been on MacRumors contributing to the conversation and offering support. Suddenly I was suspended. 

As you are aware I spent countless hours over a week putting together a ecstatically pleasing theme to make these ugly devices better and spent time engaging in productive conversations in the only thread about hacking this device online.
I have been working tirelessly the past 2 weeks to reverse engineer with the help of Ludwigs custom firmware 3 core files which are the main workhorse of this dongle. I even went as far to purchase a 2nd adapter for development purpose. 
I was able to pull apart some binary files decompile and recompile the code that could allow changes in the firmware. I was able to confirm this by actually editing the “Settings Menu” and even adding toggles for the settings you see at 192.168.50.2 contained in the firmware file onto the screen! Something I was not able to do in the ui theme file as I mentioned this was hard coded into the firmware.
I came here on Friday afternoon to post my findings and post an update to the UI theme with the new Settings screen. We have a lot more access to rebuild and access the hardware then I originally thought. 
As I was in the process of writing my post I received a message from the Moderator who suspended me and then immediately blocked me from even replying to him.

I was informed: 

My theme is not welcome here and MacRumors does not approve of my “self promotion” - I am not sure what this means. I don’t receive monetary compensation for anything I do here and all I do is come here to help and answer questions in this thread to make this device less suck and contribute to this project. 
I have decided public development of the UI THEME will halt and new firmware findings will be kept private and used to further develop and attempt to fix my own bugs for my vehicles and not released to public.
I wish everyone the best, the Original UI theme is still available for download on GitHub but I will no longer support it publicly with bugs or improvements.
It’s power trippers like these mods who cause developers like us to leave and abandon these projects. Further digging into this joke forum I see many people that contribute here are banned or suspended by mods. 
I have to much to offer and I will not be feeding this community forum with any information further, it’s unfortunate that there is no other active community working on this dongle and we have mods runs this board like a dictatorship with absurd rules — but it is what it is.
